### ISSUE TITLE
`React.PropTypes` is deprecated, might want to switch syntax

### ISSUE THREAD

**Issue by kjleitz** [learn-co-students/react-prop-types-v-000#1]
As of React v15.5, apparently `React.Proptypes` is deprecated, and the `prop-types` lib should be used. So, like this:

```js
import PropTypes from 'prop-types';

class Greeting extends React.Component {
  render() {
    return (
      <h1>Hello, {this.props.name}</h1>
    );
  }
}

Greeting.propTypes = {
  name: PropTypes.string
};
```

...as opposed to using `React.PropTypes` like the README syntax.

I haven't tried out the old method with the labs after this lesson, but since the previous lab installed a version > 15.5, I assume it will be deprecated in the rest as well. Probably not breaking, but might be good to note.

See the disclaimer at the top of the documentation on [Typechecking with PropTypes](https://facebook.github.io/react/docs/typechecking-with-proptypes.html) for more info.

**Comment by Lukeghenco** [comment]
Thanks @kjleitz this should be resolved from the latest PR.
